apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-ingress
  labels:
    {{- include "NotifyBC.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: mongodb
  ingress:
    - ports:
        - protocol: TCP
          port: 27017
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "NotifyBC.name" . }}
  policyTypes:
    - Ingress